import assert from "node:assert/strict";
import test from "node:test";

import { analyzeBuffer } from "../src/analyzer.js";
import { sequenceContextFromNodes } from "../src/frame-header-parser.js";
import { makeIvf, makeObu } from "./fixtures.js";

class BitFixture {
  constructor() { this.bits = []; }
  write(value, width) {
    for (let shift = width - 1; shift >= 0; shift -= 1) this.bits.push((value >> shift) & 1);
    return this;
  }
  finishTrailingBits() {
    this.bits.push(1);
    while (this.bits.length % 8) this.bits.push(0);
    const bytes = Buffer.alloc(this.bits.length / 8);
    this.bits.forEach((bit, index) => { bytes[index >> 3] |= bit << (7 - (index & 7)); });
    return bytes;
  }
}

function makeMultiOperatingPointSequenceHeader() {
  const bits = new BitFixture();
  bits.write(0, 3).write(0, 1).write(0, 1); // profile, still_picture, reduced
  bits.write(1, 1).write(1, 32).write(30, 32).write(1, 1).write(1, 1); // timing + UVLC(0)
  bits.write(1, 1).write(2, 5).write(1, 32).write(2, 5).write(3, 5); // decoder model
  bits.write(1, 1).write(1, 5); // initial delay present, two operating points
  bits.write(0, 12).write(0, 5).write(1, 1).write(2, 3).write(3, 3).write(0, 1).write(1, 1).write(4, 4);
  const layerIdc = (1 << 2) | (1 << 9);
  bits.write(layerIdc, 12).write(8, 5).write(1, 1).write(0, 1).write(0, 1);
  bits.write(3, 4).write(3, 4).write(15, 4).write(15, 4); // max frame 16x16
  bits.write(1, 1).write(0, 4).write(0, 3); // frame ids, total id length 3
  bits.write(0, 1).write(0, 1).write(0, 1); // superblock/filter intra/intra edge
  bits.write(0, 1).write(0, 1).write(1, 1).write(0, 1).write(1, 1); // inter tools + order hints
  bits.write(0, 1).write(0, 1).write(1, 1).write(1, 1).write(2, 3); // hint tools + screen/integer + hint bits
  bits.write(0, 1).write(0, 1).write(0, 1); // superres, CDEF, restoration
  bits.write(0, 1).write(0, 1).write(0, 1); // 8 bit, not monochrome, no color description
  bits.write(0, 1).write(0, 2).write(0, 1); // limited range, chroma position, shared UV delta
  bits.write(1, 1); // film grain present
  return bits.finishTrailingBits();
}

test("extracts a complete reduced still-picture Sequence Header with absolute bit ranges", () => {
  // Generated by FFmpeg/libaom for a 16x16 reduced still picture.
  const payload = Buffer.from("180cffda0080", "hex");
  const sequenceHeader = makeObu({ type: 1, payload });
  const ivf = makeIvf([{ payload: sequenceHeader }]);
  const report = analyzeBuffer(ivf);

  const values = Object.fromEntries(
    report.syntaxNodes.map(({ path, value }) => [path, value]),
  );
  assert.equal(values["sequence_header.seq_profile"], 0);
  assert.equal(values["sequence_header.still_picture"], 1);
  assert.equal(values["sequence_header.reduced_still_picture_header"], 1);
  assert.equal(
    values["sequence_header.operating_points[0].seq_level_idx"],
    0,
  );
  assert.equal(values["sequence_header.frame_width_bits_minus_1"], 3);
  assert.equal(values["sequence_header.frame_height_bits_minus_1"], 3);
  assert.equal(values["sequence_header.max_frame_width_minus_1"], 15);
  assert.equal(values["sequence_header.max_frame_height_minus_1"], 15);

  const payloadStartBit = report.obus[0].payloadRange.start * 8;
  assert.deepEqual(report.syntaxNodes[0].bitRange, {
    startBit: payloadStartBit,
    lengthBits: 3,
  });
  const maxHeightNode = report.syntaxNodes.find(({ path }) => path === "sequence_header.max_frame_height_minus_1");
  assert.deepEqual(maxHeightNode.bitRange, { startBit: payloadStartBit + 22, lengthBits: 4 });
  assert.equal(report.syntaxNodes.at(-1).path, "sequence_header.trailing_bits.trailing_zero_bit[7]");
  assert.equal(report.obus[0].syntaxStatus, "complete");
  assert.equal(report.obus[0].parsedPayloadBitLength, 48);
  assert.equal(report.obus[0].complete, true);
  assert.equal(report.diagnostics.length, 0);
});

test("reports a truncated Sequence Header without publishing out-of-range fields", () => {
  const sequenceHeader = makeObu({ type: 1, payload: Buffer.from([0x18]) });
  const report = analyzeBuffer(sequenceHeader);

  assert.equal(report.obus[0].syntaxStatus, "error");
  assert.ok(
    report.diagnostics.some(
      ({ code }) => code === "SEQUENCE_HEADER_TRUNCATED",
    ),
  );
  const payloadEndBit =
    (report.obus[0].payloadRange.start + report.obus[0].payloadRange.length) * 8;
  for (const node of report.syntaxNodes) {
    assert.ok(node.bitRange.startBit + node.bitRange.lengthBits <= payloadEndBit);
  }
});

test("parses multiple operating points and exposes decoder-model context", () => {
  const payload = makeMultiOperatingPointSequenceHeader();
  const report = analyzeBuffer(makeObu({ type: 1, payload }));
  const values = Object.fromEntries(report.syntaxNodes.map(({ path, value }) => [path, value]));
  const layerIdc = (1 << 2) | (1 << 9);

  assert.equal(report.obus[0].syntaxStatus, "complete");
  assert.equal(report.diagnostics.length, 0);
  assert.equal(values["sequence_header.operating_points_cnt_minus_1"], 1);
  assert.equal(values["sequence_header.operating_points[0].decoder_buffer_delay"], 2);
  assert.equal(values["sequence_header.operating_points[0].initial_display_delay_minus_1"], 4);
  assert.equal(values["sequence_header.operating_points[1].operating_point_idc"], layerIdc);
  assert.equal(values["sequence_header.operating_points[1].seq_tier"], 1);
  const context = sequenceContextFromNodes(report.syntaxNodes);
  assert.equal(context.bufferRemovalTimeLengthMinus1, 2);
  assert.equal(context.framePresentationTimeLengthMinus1, 3);
  assert.deepEqual(context.operatingPoints, [
    { operatingPointIdc: 0, decoderModelPresent: true },
    { operatingPointIdc: layerIdc, decoderModelPresent: false },
  ]);
});

test("a non-Sequence Header OBU has no syntax parse obligation", () => {
  const report = analyzeBuffer(makeObu({ type: 2 }));
  assert.equal(report.obus[0].syntaxStatus, "not_applicable");
  assert.deepEqual(report.obus[0].syntaxNodeIds, []);
  assert.equal(report.syntaxNodes.length, 0);
});
